### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/wheel-of-fortune#1]
# Motivation
We want to be able to display a basic webpage.

# Tasks
- [x] Look through the react boilerplate that I created.
- [x] Copy all the necessary dependent frameworks and files.
- [x] Verify that the web app can be loaded locally.
- [x] Be able to run on Heroku.
