### ISSUE TITLE
User can click on Carousel to switch between images.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/wheel-of-fortune#5]
# Motivation
Now that we can see the first slide, we want to be able to interact with the canvas. We will start by creating an interface of two buttons to be able to switch between images back and forth.

# Tasks
- [x] Get SVG images to be able to use for the icons.
- [x] Place SVG images on the left and right parts of the carousel.
- [x] Make sure that the arrows are re-sized with the screen.
- [x] Be able to register an event when clicking on the arrows.
- [x] Find sources for more images.
- [x] Be able to click in one direction to switch between images.
- [x] Be able to click in the other direction to go backwards.
- [x] Be able to transition smoothly between images on a click event of the arrows.
- [x] Make sure the text transitions as well to create proper flow.
