### ISSUE TITLE
User can click on dots to change the Carsousel picture. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/wheel-of-fortune#7]
# Motivation
We want to be able to interact with dots to snap to pictures in the gallery.

# Tasks
- [x] Be able to render a bar of dots under the sentence.
- [x] Be able to on a transition created a filled circle.
- [x] Be able to on a transition switch the circle and re-render it to the proper circle.
- [x] Be able to register an event on a circle.
- [x] Define Geometry for checking on a clicked circle.
- [x] Be able to register a transition to a clicked circle.
- [x] Define a transition event to a clicked circle.
- [x] Verify that the transitions work as intended.
- [x] Be able to make it so that the transitions only work while the timeout isn't proc'd.
