### ISSUE TITLE
Optimization and Writeup

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/wheel-of-fortune#9]
# Motivation
Now that we have implemented the essentials, the write up and the a few stylistic optimizations are going to be done.

# Tasks
- [x] Fix some CSS issues.
- [x] Write up the github.
- [x] Record usage on a gif.
- [x] Draw arrows from the dot menu instead of embeded on canvas.
- [x] Make sure that the arrow handlers can register the same event as the one on a normal canvas region edge click.
- [x] Line up the styles so that they work and are symmetrical.
- [x] Fix an issue with some assets not loading on time. 
- [x] Record a new demo with new assets.

# Demo
![demo](https://user-images.githubusercontent.com/26865352/50743123-0286d400-11c9-11e9-83d5-1b8d47c3c9a7.gif)
